from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from mvp_cpt_pg.schemas import PreferenceAgentResponse
from mvp_cpt_pg.utils import ensure_dir


PROFILES = {
    "conservative": {
        "risk_budget": (0.03, 0.18),
        "max_single_weight": (0.02, 0.06),
        "turnover_cap": (0.05, 0.18),
        "diversification_target": (20, 80),
    },
    "balanced": {
        "risk_budget": (0.12, 0.35),
        "max_single_weight": (0.03, 0.10),
        "turnover_cap": (0.08, 0.28),
        "diversification_target": (15, 60),
    },
    "aggressive": {
        "risk_budget": (0.25, 0.65),
        "max_single_weight": (0.05, 0.18),
        "turnover_cap": (0.15, 0.50),
        "diversification_target": (8, 35),
    },
}


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate market-aware dynamic preference paths")
    parser.add_argument("--seed", type=int, default=7, help="Base random seed")
    parser.add_argument(
        "--market-context",
        type=Path,
        default=ROOT / "artifacts" / "inputs" / "market_context_20250515_20260512.csv",
        help="CSV generated by scripts/prefetch_market_cache.py",
    )
    parser.add_argument("--output-dir", type=Path, default=ROOT / "artifacts" / "inputs")
    args = parser.parse_args()

    market_context = load_market_context(args.market_context)
    output_dir = ensure_dir(args.output_dir)
    for index, profile in enumerate(PROFILES):
        frame = build_path(profile, market_context, seed=args.seed + index * 997)
        output_path = output_dir / f"preference_path_{profile}_{len(frame)}d.csv"
        frame.to_csv(output_path, index=False, encoding="utf-8-sig")
        print(f"{profile}: {output_path}")


def load_market_context(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Market context file is missing: {path}")
    frame = pd.read_csv(path, dtype={"trade_date": str})
    required = {
        "trade_date",
        "market_ret_mean",
        "market_ret_std",
        "advancing_ratio",
        "declining_ratio",
        "turnover_rate_mean",
        "news_total_count",
        "news_total_positive",
        "news_total_negative",
    }
    missing = required.difference(frame.columns)
    if missing:
        raise ValueError(f"Market context is missing required columns: {sorted(missing)}")
    frame = frame.sort_values("trade_date").tail(240).reset_index(drop=True)
    if len(frame) != 240:
        raise ValueError(f"Market context has {len(frame)} rows, expected 240")
    return frame


def build_path(profile: str, market_context: pd.DataFrame, seed: int) -> pd.DataFrame:
    if profile not in PROFILES:
        raise ValueError(f"Unknown profile: {profile}")
    rng = np.random.default_rng(seed)
    spec = PROFILES[profile]
    signals = market_signals(market_context)
    risk_budget = market_adjusted_series(
        rng,
        spec["risk_budget"],
        base=0.55 + 0.30 * signals["risk_on"] - 0.25 * signals["stress"],
        noise=0.012,
    )
    turnover_cap = market_adjusted_series(
        rng,
        spec["turnover_cap"],
        base=0.40 + 0.35 * signals["attention"] + 0.15 * signals["abs_return"] - 0.20 * signals["stress"],
        noise=0.010,
    )
    diversification_target = market_adjusted_series(
        rng,
        spec["diversification_target"],
        base=0.45 + 0.40 * signals["stress"] - 0.25 * signals["risk_on"],
        noise=2.0,
    )
    max_single_weight = market_adjusted_series(
        rng,
        spec["max_single_weight"],
        base=0.55 + 0.30 * signals["risk_on"] - 0.35 * signals["stress"],
        noise=0.004,
    )
    frame = pd.DataFrame(
        {
            "trade_date": market_context["trade_date"].astype(str),
            "risk_budget": np.round(risk_budget, 4),
            "max_single_weight": np.round(max_single_weight, 4),
            "turnover_cap": np.round(turnover_cap, 4),
            "diversification_target": np.clip(np.rint(diversification_target), 1, 100).astype(int),
            "style_tilt": style_path_from_market(profile, signals),
        }
    )
    validate(frame)
    return frame


def market_signals(market_context: pd.DataFrame) -> pd.DataFrame:
    ret = pd.to_numeric(market_context["market_ret_mean"], errors="coerce").fillna(0.0)
    cross_vol = pd.to_numeric(market_context["market_ret_std"], errors="coerce").fillna(0.0)
    advancing = pd.to_numeric(market_context["advancing_ratio"], errors="coerce").fillna(0.5)
    declining = pd.to_numeric(market_context["declining_ratio"], errors="coerce").fillna(0.5)
    turnover = pd.to_numeric(market_context["turnover_rate_mean"], errors="coerce").ffill().bfill().fillna(0.0)
    news_count = pd.to_numeric(market_context["news_total_count"], errors="coerce").fillna(0.0)
    news_pos = pd.to_numeric(market_context["news_total_positive"], errors="coerce").fillna(0.0)
    news_neg = pd.to_numeric(market_context["news_total_negative"], errors="coerce").fillna(0.0)
    wealth = (1.0 + ret).cumprod()
    drawdown = (wealth.cummax() - wealth) / wealth.cummax().replace(0.0, np.nan)
    sentiment = ((news_pos - news_neg) / news_count.clip(lower=1.0)).clip(-1.0, 1.0)
    signals = pd.DataFrame(
        {
            "momentum": rank01(ret.rolling(5, min_periods=1).mean()),
            "abs_return": rank01(ret.abs()),
            "volatility": rank01(cross_vol),
            "breadth": advancing - declining,
            "turnover": rank01(turnover),
            "attention": rank01(np.log1p(news_count)),
            "sentiment": sentiment,
            "drawdown": rank01(drawdown.fillna(0.0)),
        }
    )
    signals["risk_on"] = (
        0.45 * signals["momentum"]
        + 0.25 * rank01(signals["breadth"])
        + 0.20 * rank01(signals["sentiment"])
        + 0.10 * signals["turnover"]
    ).clip(0.0, 1.0)
    signals["stress"] = (
        0.45 * signals["volatility"]
        + 0.30 * signals["drawdown"]
        + 0.25 * rank01(-signals["sentiment"])
    ).clip(0.0, 1.0)
    return signals


def rank01(values: pd.Series | np.ndarray) -> pd.Series:
    series = pd.Series(values, dtype=float)
    if series.nunique(dropna=True) <= 1:
        return pd.Series(np.full(len(series), 0.5), index=series.index)
    return series.rank(pct=True).astype(float)


def market_adjusted_series(
    rng: np.random.Generator,
    bounds: tuple[float, float],
    *,
    base: pd.Series,
    noise: float,
) -> np.ndarray:
    low, high = bounds
    base = pd.Series(base, dtype=float).clip(0.0, 1.0)
    values = low + (high - low) * base
    innovations = rng.normal(0.0, noise, len(values))
    for idx in range(1, len(values)):
        innovations[idx] = 0.85 * innovations[idx - 1] + 0.15 * innovations[idx]
    return np.clip(values + innovations, low, high)


def style_path_from_market(profile: str, signals: pd.DataFrame) -> list[str]:
    styles = []
    for _, row in signals.iterrows():
        if row["stress"] > 0.70:
            styles.append("low_vol" if profile != "aggressive" else "quality")
        elif row["risk_on"] > 0.70 and row["attention"] > 0.55:
            styles.append("momentum" if profile == "aggressive" else "balanced")
        elif row["sentiment"] < -0.20:
            styles.append("quality")
        elif row["drawdown"] > 0.65:
            styles.append("value" if profile != "conservative" else "quality")
        elif profile == "conservative":
            styles.append("balanced" if row["risk_on"] > 0.55 else "low_vol")
        elif profile == "balanced":
            styles.append("value" if row["turnover"] < 0.45 else "balanced")
        else:
            styles.append("momentum" if row["risk_on"] > 0.55 else "value")
    return styles


def validate(frame: pd.DataFrame) -> None:
    for row in frame.to_dict("records"):
        PreferenceAgentResponse.from_dict({"preference_vector": row})


if __name__ == "__main__":
    main()
